"""
Claims Readiness panel
======================
Launch-readiness checklist for the Claims department: policy wording review,
operational setup in ClaimCenter, and post-launch monitoring. Guidance text is
generated by backend/readiness.py from the brief's claims analytics.
"""
from __future__ import annotations

from typing import Any, Callable, Dict, Optional

import streamlit as st

STATUS_ICON = {"Not started": "⚪", "In progress": "🟡", "Done": "✅", "N/A": "➖"}


def _md(text: Optional[str]) -> str:
    return (text or "").replace("$", "\\$")


def render_readiness(brief: Dict[str, Any], data: Optional[Dict[str, Any]],
                     save_item: Callable[[str, Dict[str, str]], bool]) -> None:
    """Render the checklist. *save_item(item_id, {status, owner, note})* persists one item."""
    st.markdown("### Claims Readiness")
    st.caption("What Claims must have in place before this product launches. Guidance is tailored from this brief's "
               "claims data; status, owner and notes are recorded per item.")
    if not data:
        st.error("Could not load the readiness checklist from the backend.")
        return

    summary, items, stages, statuses = data["summary"], data["items"], data["stages"], data["statuses"]
    if brief.get("claims_status") != "Approved":
        st.info("The Claims finding is not approved yet. You can start preparing, but launch readiness should only "
                "be signed off after the Claims finding is approved.")

    # --- Summary ---
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Required items complete", f"{summary['required_complete']} / {summary['required_total']}")
    c2.metric("Readiness", f"{summary['percent_complete']:.0f}%")
    c3.metric("In progress", summary["in_progress"])
    c4.metric("Launch status", "Ready" if summary["ready"] else "Not ready")
    st.progress(summary["percent_complete"] / 100)
    if summary["ready"]:
        st.success("All required Claims readiness items are Done or N/A. Claims is ready to support launch.")

    # --- Items by stage ---
    for stage_key, stage_label in stages.items():
        stage_items = [i for i in items if i["stage"] == stage_key]
        s = summary["by_stage"][stage_key]
        st.markdown(f"#### {stage_label} · {s['complete']}/{s['total']} complete")
        for item in stage_items:
            icon = STATUS_ICON.get(item["status"], "⚪")
            owner = f" · 👤 {item['owner']}" if item["owner"] else ""
            optional = "" if item["required"] else " _(optional)_"
            with st.expander(f"{icon} {item['title']} — {item['status']}{owner}", expanded=False):
                st.markdown(f"{_md(item['guidance'])}{optional}")
                key = f"rd_{brief['id']}_{item['id']}"
                with st.form(key=f"{key}_form", border=False):
                    c1, c2 = st.columns([1, 2])
                    status = c1.selectbox("Status", statuses, index=statuses.index(item["status"]), key=f"{key}_status")
                    owner_val = c2.text_input("Owner", value=item["owner"], key=f"{key}_owner",
                                              placeholder="e.g. Claims Ops Manager")
                    note_val = st.text_area("Notes / evidence", value=item["note"], key=f"{key}_note", height=90,
                                            placeholder="Decision taken, document link, open issues...")
                    if st.form_submit_button("Save", type="primary"):
                        if save_item(item["id"], {"status": status, "owner": owner_val, "note": note_val}):
                            st.rerun()
                if item.get("updated_at"):
                    st.caption(f"Last updated {item['updated_at'][:16].replace('T', ' ')} UTC")
