"""
Database connection helper for the Roundtable analytics layer.

Provides a single connection factory pointing at the existing
roundtable.db generated by data/generate_data.py.
"""
from __future__ import annotations

import sqlite3
from pathlib import Path

# roundtable.db lives at the workspace root, one level above backend/
DB_PATH = Path(__file__).resolve().parent.parent / "roundtable.db"


def get_connection() -> sqlite3.Connection:
    """Return a new SQLite connection to roundtable.db.

    The connection uses Row factory so results can be accessed by
    column name as well as index.
    """
    if not DB_PATH.exists():
        raise FileNotFoundError(
            f"Database not found at {DB_PATH}. "
            f"Run data/generate_data.py first to create it."
        )
    conn = sqlite3.connect(str(DB_PATH))
    conn.row_factory = sqlite3.Row
    return conn
